cgi_recover:cgi_recover.o public_handle.o
	gcc -o cgi_recover cgi_recover.o public_handle.o
cgi_recover.o:cgi_recover.c
	gcc -c cgi_recover.c
public_handle.o:../socket_public/public_handle.c
	gcc -c ../socket_public/public_handle.c
