cgi_delete:cgi_getlist.o public_handle.o
	gcc -o cgi_delete cgi_delete.o public_handle.o
cgi_delete.o:cgi_delete.c
	gcc -c cgi_delete.c
public_handle.o:../socket_public/public_handle.c
	gcc -c ../socket_public/public_handle.c

